fix meshgrid binning
XENONnT/appletree pull request #101
Opened 2023-06-16 14:21 UTC by hoetzsch

Meshgrid binning fix (by Zihao). To be nicified

2023-06-16 14:34 UTC, dachengx commented on appletree/likelihood.py
> +            if type(self._bins[0]) == int:
Please use `isinstance()` here.

2023-06-16 14:35 UTC, dachengx commented on appletree/likelihood.py
> +            if type(self._bins[1]) == int:
Also `isinstance()` here.

2023-06-16 14:36 UTC, dachengx requested changes
Thanks, @hoetzsch . After the requested changes are met, I think it is good to merge.

2023-06-16 15:49 UTC, hoetzsch commented
@dachengx thanks, changed it!

2023-06-18 13:14 UTC, dachengx approved these changes
I added some tests and warnings. Looks good now.

2023-06-18 13:14 UTC, merged