Add efield position dependence
XENONnT/appletree pull request #188
Opened 2024-09-29 16:15 UTC by mhliu0001

Previously, only one uniform electric field was used. This PR adds position dependence to the electric field.

Another change is that I have unified the nestv2 parameter name with the other yield models. The field parameter was called "literature_field" before, and we should change it to "field" to avoid confusion.

2024-09-29 16:48 UTC, mhliu0001 commented
I need to write a test for the field dependence.

2024-10-01 19:02 UTC, dachengx commented
LGTM

1. We will need to change `parameters["field"]` in https://github.com/XENONnT/applefiles accordingly.
2. This PR is not for production in SR1. So it is not in a hurry to merge it now.

2024-10-01 19:03 UTC, dachengx requested changes
Please generate `_efield_map.json` mimicking https://github.com/XENONnT/appletree/blob/88445b55f5e46dd8282b7a57c795a59a0fd8fb3c/notebooks/6.%20maps.ipynb.

2026-04-22 17:18 UTC, mhliu0001 commented
This would be considered in a different PR

2026-04-22 17:18 UTC, closed without merging