use mongo downloader in utilix
XENONnT/appletree pull request #190
Opened 2024-10-11 01:45 UTC by yuema137

As discussed and implemented here: https://github.com/XENONnT/utilix/pull/141
We propose to move the DB-related operations to `utilix` to reduce `straxen` dependency, as importing `straxen` usually takes some time

2024-10-11 01:50 UTC, dachengx approved these changes

2024-10-11 05:22 UTC, dachengx requested changes
Thanks @yuema137 , please also remove `straxen` from `pyproject.toml`.

2024-10-11 17:37 UTC, yuema137 commented
@dachengx Thanks.I double-checked that there's no remaining `straxen` dependency and removed the requirement

2024-10-11 17:37 UTC, zihaoxu98 approved these changes

2024-10-12 15:13 UTC, merged

2024-10-12 15:21 UTC, dachengx commented on pyproject.toml
>  graphviz = "*"
Please add `utilix = ">=0.10.1"` here.