More options for get_post_parameters
XENONnT/appletree pull request #193
Opened 2024-11-19 14:43 UTC by zihaoxu98

This PR adds more options for `context.get_post_parameters`. The user can get the point estimator from the posterior, by setting `which` to `'mpe'` (max-posterior estimation), `'median'` (marginalized medians), `'random'` (random sample from walker).

This solves https://github.com/XENONnT/appletree/issues/186

2024-11-19 15:03 UTC, zihaoxu98 commented
pre-commit fails due to this https://github.com/PyCQA/docformatter/issues/293

2024-11-26 19:35 UTC, dachengx requested changes

2024-11-26 19:35 UTC, dachengx commented on appletree/context.py
> +            which: str, 'mpe', 'random' or 'median'.
Please add comments about what they are.

2024-11-26 20:12 UTC, zihaoxu98 commented on appletree/context.py
> +            which: str, 'mpe', 'random' or 'median'.
Added

2024-11-26 20:31 UTC, dachengx approved these changes

2024-11-26 20:31 UTC, merged